[versions]
appcompat = "1.6.1"
cardview = "1.0.0"
constraintlayout = "2.1.4"
core-ktx = "1.12.0"
recyclerview = "1.3.2"
espresso-core = "3.5.1"
runner = "1.5.2"
junit = "4.13.2"
agp = "8.2.1"
kotlin = "1.9.0"
spotless = "6.24.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
